name: Build Ruby Docker Image
on:
  push:
    branches:
      - implement
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      - name: Build and Push HOMER Docker image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_HOMER_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_HOMER_REPOSITORY }}:${{ github.sha }}
        working-directory: homer
      - name: Build and Push LISA Docker image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_LISA_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_LISA_REPOSITORY }}:${{ github.sha }}
        working-directory: lisa